[project]
name = "csmap-qgis-plugin"
version = "0.0.1"
description = ""
authors = [
    {name = "MIERUNE Inc.", email = "info@mierune.co.jp"},
]
readme = "README.md"
requires-python = ">=3.9"

dependencies = []

[project.optional-dependencies]
dev = [
    "ruff>=0.4.5",
    "rasterio>=1.3.10",
]
