name: Lint

on:
    pull_request:
        branches: [main]
    workflow_dispatch:
jobs:
    Test:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install poetry
              run: python -m pip install poetry

            - uses: actions/setup-python@v4
              with:
                  python-version: '3.9'

            - name: Install dependencies
              run: poetry install

            - name: Lint with ruff
              run: poetry run ruff --output-format=github .

            - name: Format with ruff
              run: poetry run ruff format .
